import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d

import hierarchic_shape_functions as hsf

x = np.linspace(-1, 1, 50)
y = np.linspace(-1, 1, 50)
X, Y = np.meshgrid(x, y)
N1 = list()
N2 = list()
N3 = list()
N4 = list()
N5 = list()
N6 = list()
N7 = list()
N8 = list()
N9 = list()
N10 = list()
N11 = list()
N12 = list()
N13 = list()
N14 = list()
N15 = list()
N16 = list()
for eta in y:
    for xi in x:
        N = hsf.shape_functions_2d(xi, eta, 3)
        N1.append(N[1-1])
        N2.append(N[2-1])
        N3.append(N[3-1])
        N4.append(N[4-1])
        N5.append(N[5-1])
        N6.append(N[6-1])
        N7.append(N[7-1])
        N8.append(N[8-1])
        N9.append(N[9-1])
        N10.append(N[10-1])
        N11.append(N[11-1])
        N12.append(N[12-1])
        N13.append(N[13-1])
        N14.append(N[14-1])
        N15.append(N[15-1])
        N16.append(N[16-1])

size = int(np.sqrt(len(N1)))
N1 = np.array(N1).reshape((size, size))
N2 = np.array(N2).reshape((size, size))
N3 = np.array(N3).reshape((size, size))
N4 = np.array(N4).reshape((size, size))
N5 = np.array(N5).reshape((size, size))
N6 = np.array(N6).reshape((size, size))
N7 = np.array(N7).reshape((size, size))
N8 = np.array(N8).reshape((size, size))
N9 = np.array(N9).reshape((size, size))
N10 = np.array(N10).reshape((size, size))
N11 = np.array(N11).reshape((size, size))
N12 = np.array(N12).reshape((size, size))
N13 = np.array(N13).reshape((size, size))
N14 = np.array(N14).reshape((size, size))
N15 = np.array(N15).reshape((size, size))
N16 = np.array(N16).reshape((size, size))

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N1, cmap='coolwarm')
ax.set_axis_off()
ax.set(zlim=[-1,1])

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N2, cmap='coolwarm')
ax.set_axis_off()
ax.set(zlim=[-1,1])

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N3, cmap='coolwarm')
ax.set_axis_off()
ax.set(zlim=[-1,1])

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N4, cmap='coolwarm')
ax.set_axis_off()
ax.set(zlim=[-1,1])

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N5, cmap='coolwarm')
ax.set_axis_off()

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N6, cmap='coolwarm')
ax.set_axis_off()

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N7, cmap='coolwarm')
ax.set_axis_off()

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N8, cmap='coolwarm')
ax.set_axis_off()

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N9, cmap='coolwarm')
ax.set_axis_off()

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N10, cmap='coolwarm')
ax.set_axis_off()

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N11, cmap='coolwarm')
ax.set_axis_off()

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N12, cmap='coolwarm')
ax.set_axis_off()

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N13, cmap='coolwarm')
ax.set_axis_off()

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N14, cmap='coolwarm')
ax.set_axis_off()

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N15, cmap='coolwarm')
ax.set_axis_off()

plt.figure()
ax = plt.axes(projection='3d')
ax.plot_surface(X, Y, N16, cmap='coolwarm')
ax.set_axis_off()

plt.show()
